/**
 * This file was auto-generated by openapi-typescript from backend OpenAPI schemas.
 * Do not edit this file directly.
 * Generated at: 2026-09-16T14:12:48.241Z
 */

export interface paths {
  '/api/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check / Ping
     * @description Returns server health status and current timestamp.
     */
    get: operations['PingController_ping'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PingResponseDto: {
      /**
       * @description Status message indicating API responsiveness
       * @example pong
       */
      message: string;
      /**
       * @description ISO-8601 timestamp of when the ping was processed
       * @example 2026-09-15T12:00:00.000Z
       */
      timestamp: string;
      /**
       * @description Correlation ID assigned to the request trace
       * @example d9b2d63d-a233-4123-8478-f3d919712001
       */
      correlationId?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  PingController_ping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is healthy and responsive. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PingResponseDto'];
        };
      };
    };
  };
}

// Helper types and aliases for convenient client consumption
export type Schema<T extends keyof components['schemas']> = components['schemas'][T];

export type PingResponseDto = components['schemas']['PingResponseDto'];
export type PingResponse = PingResponseDto;

export const API_INFO = {
  title: 'Atiesh Codex API',
  version: '1.0.0',
};
